# lasso config - lasso is an open source OpenID connect service
# which we use to connect to Single Sign-On providers

lasso:
  # Uncomment the following line to enable debug logging for the authentication service
  logLevel: debug
  domains:
  # This domain must match the hostname of the server (set in the config/access_config section)
  # and must also match the domain of the callback_url here, and the redirect URL set in Azure AD
    - {{HOSTNAME}}
  whiteList:
  #  - List of email addresses you'd like to accept
  # - OR -
  # set allowAllUsers: true to accept anyone who can authenticate to Azure AD
  allowAllUsers: true

oauth:
  # Specific information for connecting to Azure AD
  # The client_id was generated upon App registration in Azure AD
  # The *_url information is set using the MS Tenant ID for Wabtec
  # e.g. https://login.microsoftoneline.com/{tenant_id}/oath2/...
  # The callback_url is manually set upon App registration, and the value here
  # *MUST* match the value inside the Azure AD registered application
  provider: oidc
  client_id: {{CLIENT_ID}}
  client_secret: {{CLIENT_SECRET}}
  auth_url: {{AUTH_URL}}
  token_url: {{TOKEN_URL}}
  user_info_url: {{USER_INFO_URL}}
  scopes:
    - openid
    - email
    - profile
    - groups
  callback_url: https://{{HOSTNAME}}/auth
